/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androiddemo_activity_HelloJniActivity */

#ifndef _Included_com_example_androiddemo_activity_HelloJniActivity
#define _Included_com_example_androiddemo_activity_HelloJniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androiddemo_activity_HelloJniActivity
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_stringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androiddemo_activity_HelloJniActivity
 * Method:    unimplementedStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_unimplementedStringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_example_androiddemo_activity_HelloJniActivity
 * Method:    getIntAtIndex
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_getIntAtIndex
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_example_androiddemo_activity_HelloJniActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
