/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "com_example_androiddemo_activity_HelloJniActivity.h"

JNIEXPORT jstring JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_stringFromJni(
		JNIEnv * env, jobject obj) {

#ifdef __cplusplus
	return env->NewStringUTF("Hello Jni for C++!");
#else
	return (*env)->NewStringUTF(env, "Hello Jni for C!");
#endif
}

JNIEXPORT jstring JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_unimplementedStringFromJni(
		JNIEnv * env, jobject obj) {
#ifdef __cplusplus
	return NULL;
#else
	return NULL;
#endif
}

JNIEXPORT jint JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_add(
		JNIEnv * env, jobject obj, jint a, jint b) {
#ifdef __cplusplus
	return a + b;
#else
	return a + b;
#endif
}

JNIEXPORT jint JNICALL Java_com_example_androiddemo_activity_HelloJniActivity_getIntAtIndex(
		JNIEnv *env, jobject obj, jintArray array, jint i) {
#ifdef __cplusplus
	jint* intBuffer = (env)->GetIntArrayElements(array, NULL);
	(env)->ReleaseIntArrayElements(array, intBuffer, 0);
	return intBuffer[i];
#else
	jint* intBuffer = (*env)->GetIntArrayElements(env, array, NULL);
	(*env)->ReleaseIntArrayElements(env, array, intBuffer, 0);
	return intBuffer[i];
#endif
}

